### PR TITLE
support `goon:"kind,FooKind"` syntax

### PR DESCRIPTION
**Pull request by vvakame**
@laco0416 do you like `NewSampleQueryBuilderWith(entity.Kind).Query().Count(c)` API?

### CODE REVIEW

**Comment by lacolaco** [comment]
What will happen on that query? please describe a short summary.

**Comment by lacolaco** [comment]
I want to see a query built from that.

**Comment by vvakame** [comment]
If you can't understanding from the code, I think it is bad code.

**Comment by lacolaco** [comment]
That name, `NewSampleQueryBuilderWith(kind)`, can be associated with which will return a merged result from`Sample` and `kind`.

**Comment by vvakame** [comment]
(´・ω・`)

**Comment by lacolaco** [comment]
As far as I see, this API can query by a kind name defined in FieldTag. In other words, this API will not use the struct name.  Right?

**Comment by vvakame** [comment]
Ya, it is right.
Do you know key specifications on goon? see https://godoc.org/github.com/mjibson/goon#hdr-Key_Specifications
goon permit us to modify `kind` name by struct tag or field value.

**Comment by lacolaco** [comment]
I think builders should use the name transparently when `goon:"kind"` exists.

**Comment by vvakame** [comment]
It is default.
please check this testcase. https://github.com/favclip/qbg/blob/34dc997b90edebb2d429a3dc7ea123d51c85ccdc/misc/fixture/f/model_test.go
We should support 'by struct tag or "field value".'. It is configurable in run time.

**Comment by lacolaco** [comment]
I prefer the below

-  `NewSampleQueryBuilderBySpecificKind("sample_2")` (too long?)
- short name:  `NewSampleQueryBuilderByKind("sample_2")`

**Comment by vvakame** [comment]
We have discussion this issue in offline.

**Pull request merged**
